AllCops:
  Exclude:
    - db/seeds.rb
    - lib/tasks/*.rake
    - config/routes.rb
    - db/migrate/*.rb
    - Rakefile
    - Gemfile
    - config/**/*
    - bin/spring
    - bundler/**/*
    - bin/**/*
    - node_modules/**/*
    - tmp/**/*
    - spec/spec_helper.rb
    - spec/factories/*

Metrics/AbcSize:
  Enabled: false
Metrics/ModuleLength:
  Max: 150
Metrics/BlockLength:
  Max: 40
Metrics/MethodLength:
  Max: 50
Metrics/LineLength:
  Max: 150
Style/IfUnlessModifier:
  Enabled: false
Style/Documentation:
  Enabled: false
  Exclude:
    - app/controllers/*
    - app/models/*
    - spec/**/*
Metrics/BlockLength:
  Exclude:
    - spec/**/*